### ISSUE TITLE
(1.16.5) Swap row and column sorting functionality

### ISSUE THREAD

**Issue by Gann4Life** [blackd/Inventory-Profiles#50]
This is a suggestion to swap functionality for buttons sorting in columns and rows, to make it more intuitive to read.
It might be something subjetctive too so if i'm heavily musunderstanding this, let me know and i'd love to see any explaination.

### Sort in columns
![image](https://user-images.githubusercontent.com/56666653/134290127-75a5caed-17f5-49bd-8beb-11abedef7796.png)
I am expecting to see items sorted like in the button, but it does not happen and makes me feel confused, the text used to feel weird to me, but i think i get what it means by "column".

### Sort in rows
![image](https://user-images.githubusercontent.com/56666653/134290324-756828ac-2699-4dcc-b313-e8b0efd11c55.png)
Literally same as above but for rows:
_I am expecting to see items sorted like in the button, but it does not happen and makes me feel confused, the text used to feel weird to me, but i think i get what it means by "rows"._

### Conclusion
I'm expecting to see items sorted the same as the button represents, the first time i used the mod it made me feel confused about how items were being sorted and i hope it makes sense for everyone too, i think that swapping the button icons will make everything feel more obvious and intuitive, maybe the texts were used in a programmer's view and not from a user point of view.

I'm not a minecraft modder yet, if i could i'd do this myself and try to contribute with the project, i'm sorry if this detail is too small for something to be done about it.

**Comment by blackd** [comment]
I haven't really messed with the sorting code so I guess the buttons are reversed in the original mod too.

I'll check it.

**Comment by Gann4Life** [comment]
I've used these buttons more times and sometimes it does the right job but sometimes it doesnt as i've shown in this "post", and now this is weird and probably has bugs, or maybe its behaving as it should, i'm not really sure, but i'll share more screenshots

### Column sorting
![image](https://user-images.githubusercontent.com/56666653/134315770-86ec37fd-ddde-4ae3-9f1b-868e459ed3ee.png)

### Row sorting
![image](https://user-images.githubusercontent.com/56666653/134315839-68d0c627-af0a-4676-bbee-d924a07d2274.png)

Side comment: Thanks for making this fork and continuing with the mod, i didn't expected such a quick answer :)
Take your time, wish you a good day/noon/night.

**Comment by blackd** [comment]
fixed in bb1ef68

**Comment by Arcami** [comment]
Still having this issue with version 1.7.0 for Minecraft 1.18.2.

**Comment by blackd** [comment]
can you post a screen shot

also can you test with 3 - 4 item types only because if the item types are too many it looks like columns and rows swap

**Comment by Arcami** [comment]
I just checked and it is as you've said. 

This is the bug I'm experimenting (with a lot of item types):
![2022-09-01_12 46 34](https://user-images.githubusercontent.com/11982824/187900155-f6add3e5-e608-4d74-835e-6f956b68d485.png)

![2022-09-01_12 46 44](https://user-images.githubusercontent.com/11982824/187900189-c2388606-bcc2-4810-896f-59aff1d1943e.png)

And with a few item types it works as expected:
![2022-09-01_13 13 20](https://user-images.githubusercontent.com/11982824/187901003-10dcf73e-9a97-412f-882c-7526131d1e6e.png)

![2022-09-01_13 13 32](https://user-images.githubusercontent.com/11982824/187901033-50605f30-bbf0-47f1-9400-3b7bded11233.png)

**Comment by blackd** [comment]
with lots of item types it just looks like it's the opposite.
also sort doesn't ignore durability and the bows for example are considered different items. So in the first screenshot you have 6 columns of bows and not 2 rows of bows

**Comment by Stetoskop** [comment]
Having the same problem, attaching screenshots.

This is a quite simple example, only three different items. The potatoes and wheat aren't indicating any grouping as seen by the glowstone dust seperating them, which is fine, but the buttons seem to be reversed.

Minecraft 1.19.2
Fabric Loader 0.14.9
IPN 1.8.2

![image](https://user-images.githubusercontent.com/13838375/198014187-f4c978d4-3e97-4660-bbd0-e8c45f86692f.png)

![image](https://user-images.githubusercontent.com/13838375/198014231-9da0317c-bfbb-4206-93de-595fbcc768d4.png)

**Comment by blackd** [comment]
Game and loader versions?

**Comment by Stetoskop** [comment]
Minecraft        1.19.2
Fabric Loader  0.14.9
IPN                 1.8.2
